# Sample .travis.yml for R projects

language: r
r:
    - release
    - devel

sudo: false
cran: http://cran.at.r-project.org

cache: packages

addons:
  apt:
    sources:
    #- ubuntu-toolchain-r-test
    packages:
    # - gcc-4.9
     # - g++-4.9

before_install:
    #- wget http://mafft.cbrc.jp/alignment/software/mafft-7.310-with-extensions-src.tgz
    #- tar -xzvf mafft-7.310-with-extensions-src.tgz
    #- pushd mafft-7.310-with-extensions && pushd core/ && make && sudo make install
    #- wget http://eddylab.org/software/hmmer3/3.1b2/hmmer-3.1b2-linux-intel-x86_64.tar.gz
    #- tar -xzvf hmmer-3.1b2-linux-intel-x86_64.tar.gz
    #- pushd hmmer-3.1b2-linux-intel-x86_64 && ./configure && make && sudo make install

r_packages:
# - covr

after_success:
#  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - NOT_CRAN: true
    - R_BUILD_ARGS="--resave-data --compact-vignettes=gs+qpdf"
    - R_CHECK_ARGS="--as-cran --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"


