# Sample .travis.yml for R projects

language: r
r:
    - release
#    - devel

cache: packages
warnings_are_errors: true
sudo: required 

# https://github.com/jimhester/rio/blob/9026180fd731aaed34f21cba3b5e207124618e5b/.travis.yml#L8-L20

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install:
    - wget http://mafft.cbrc.jp/alignment/software/mafft-7.310-with-extensions-src.tgz
    - tar -xzvf mafft-7.310-with-extensions-src.tgz
    - pushd mafft-7.310-with-extensions && pushd core/ && make && sudo make install
    - wget http://eddylab.org/software/hmmer3/3.1b2/hmmer-3.1b2-linux-intel-x86_64.tar.gz
    - tar -xzvf hmmer-3.1b2-linux-intel-x86_64.tar.gz
    - pushd hmmer-3.1b2-linux-intel-x86_64 && ./configure && make && sudo make install

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - CRAN=http://cran.rstudio.com
    - NOT_CRAN=true
 #   - CRAN: http://cran.at.r-project.org


